name = "medexplainer"
main = "functions/api/main.py"
compatibility_date = "2024-01-01"

# For Cloudflare Pages
pages_build_output_dir = "public"

[vars]
PUBMED_EMAIL = "@secrets.PUBMED_EMAIL"

# For Workers
[build]
command = "pip install -r requirements-prod.txt"

[build.upload]
format = "modules"
main = "./functions"

[[r2_buckets]]
binding = "PUBLIC_BUCKET"
bucket_name = "medexplainer-assets"
